on:
  push:
    branches:
      - feature/tomcatdeploy
jobs:
  build-and-publish:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 14                    
          server-id: github 
      - name: Configure Git user
        run: |
         git config --global user.email "anushamadhala678@gmail.com"
         git config --global user.name "anushamadhala678"

      - name: Publish war
        run: ./mvnw -B release:prepare release:perform
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
