on:
  push:
    branches:
      - feature/tomcatdeploy
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'                    
        server-id: github 
        distribution: 'temurin'
    - name: Configure Git user
      run: |
       git config --global user.email "anushamadhala678@gmail.com"
       git config --global user.name "anushamadhala678"

        
     
       
    - name: build
      run: |
       mvn -f pom.xml -B clean package
     
    - name: deleting tags
      run: |
       #git tag --delete sysfoo-0.0.24
       #git push --delete origin sysfoo-0.0.24
       git pull --tags --force 

    - name: Publish war
      run: mvn -B clean release:prepare release:perform -Dusername=${{ secrets.GITHUB_TOKEN }} -Dpassword=${{ secrets.GITHUB_TOKEN }}


