
on:
  push:
    branches:
      - feature/tomcatdeploy
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the artifacts
      run: |
        mvn -f pom.xml -B clean package
    - name: Publish the artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: "${{ github.workspace }}/target/*.war" 
  



