name: Maven Package

on:
 push:
  branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
    - name: Upload Report
      uses: actions/upload-artifact@v2
    

    - name: Upload S3    
      uses: shallwefootball/s3-upload-action@master
      id: S3
      with:
          aws_key_id: "AKIAV7C3DSPQJEX44XXJ"
          aws_secret_access_key: "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"
          #aws_bucket: bucketName
          #source_dir: cypress/reports/Result   
    - name: Link To Report
      run: echo "https://s3.amazonaws.com/bucketName/${{steps.S3.outputs.object_key}}/index.html"
   
