name: Maven Package

on:
 push:
  branches: [ feature/tomcatdeploy ]
 pull_request:
   branches: [ feature/tomcatdeploy ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -f pom.xml -B clean package
      
  deploy:
    runs-on: self-hosted
    steps:
    - name: deploy to tomcat
      run: mvn -f pom.xml clean release:prepare
    






