name: Maven Package

on:
 push:
  branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: rsync
      run: rsync --version
 
  
    - name: Deploy to Server 1
      uses: AEnterprise/rsync-deploy@v1.0
    - name: Deploy to sandbox via rsync
      uses: trendyminds/github-actions-rsync@master
      with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: /var/release
          RSYNC_SOURCE: /src/public/
      
        
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER_PORT: "22"
        ARGS: "-avz --delete "
        FOLDER: "/"
        SERVER_IP: "54.163.192.96"
        USERNAME: "root"
        SERVER_DESTINATION: "/"
   
