name: Maven Package

on:
 push:
  branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: rsync
      run: rsync --version


        
