name: Maven Package

on:
 push:
  branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -f pom.xml -B clean package
      
    - uses: chrnorm/deployment-action@v2
      name: Create GitHub deployment
      id: deployment

      with:
          token: '${{ github.token }}'
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.war"        
          
          
    - name: Publish Service
      run: mvn -f pom.xml -B clean release:prepare release:perform
      
     
         

      
      
   

   
