name: Maven Package

on:
 push:
  branches: [ feature/tomcatdeploy ]
 pull_request:
   branches: [ feature/tomcatdeploy ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -f pom.xml -B clean package
      
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
      - name: publish
        run: mvn -f pom.xml -B clean release:prepare
        
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}

    






