name: Maven Package

on:
 push:
  branches: [ feature/tomcatdeploy ]
 pull_request:
   branches: [ feature/tomcatdeploy ]

jobs:
  build:
    runs-on: self-hosted
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -f pom.xml -B clean package
      
    - uses: chrnorm/deployment-action@v2
      name: Create GitHub deployment
      id: deployment

      with:
          token: '${{ github.token }}'
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.war"         
        
          
    - name: Publish Service
      run: mvn -f pom.xml -B clean install release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Rollback Release
      if: failure() && steps.release.outputs.id != ''
      uses: author/action-rollback@stable
      with:
          # Using a known release ID
          id: ${{ steps.release.id }}
          # Using a tag name
        
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
    
        
        

        
        
      
     
         

      
      
   

   
