
on:
  push:
    branches:
      - feature/tomcatdeploy
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
     - name: Push to another repository
       uses: peter-evans/create-pull-request@v3
     - name: Configure Git user
       run: |
          git config --global user.email "anushamadhala678@gmail.com"
          git config --global user.name "anushamadhala678"
     - name: publish service
       run: mvn -f pom.xml -B clean release:prepare release:perform
       env:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Build artifacts"
        files: ${{ github.workspace }}/target/*
        branch: build-artifacts
        base: feature/tomcatdeploy
        repository: anushamadhala678/practicegit

  



