name: Maven Package

on:
 push:
  branches: [ feature/tomcatdeploy ]
 pull_request:
   branches: [ feature/tomcatdeploy ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -f pom.xml -B clean package
    - name: Configure Git user
      run: |
          git config user.email "anushamadhala678@gmail.com"
          git config user.name "anusha"
          git pull
          git push --delete origin sysfoo-0.0.22
      
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
      - name: publish
        run: mvn -f pom.xml -B clean release:prepare
        env:
          TARGET: /opt

    






